gomarkdown/markdown

- ast/attribute.go
- ast/node.go
- html/renderer.go
- parser/attribute.go
- parser/attribute_test.go
- parser/block.go
- parser/parser.go
This adds the possibility to add block level attributes:
{#id2}
> line
When enabled to will generate (for HTML) an id="id2" in the openening
tag of the block quote:
<blockquote id="id2">
<p>line</p>
</blockquote>
Only one block level attribute is allowed, if multiple are given only
the last one seen is applied, the rest is silently ignored.
The attributes are stored in *Parser and copy to the node in addBlock.
It's up to the renderer to use the attributes, the html renderer
currently only looks at the ID.
> Add block attributes

- parser/block.go
This removes the weird, add and then remove dance for the table node. It
also calls addBlock only when something is really going to be added.
> Table: add ast.Table in tableHeader

- parser/block.go
- parser/options.go
- parser/options_test.go
- parser/parser.go
Add a way to add custom parser functions that are called from the main
parser. This PR only adds a block level parsing option. It also requires
to make public: p.addChild, p.block and p.finalize.
With this in place it should be possible to parse a TOML title block
which will then be picked up the */renderer.
The test function in option_test.go is heavily inspired by function
`p.quote(data []byte) int`, (which does call addBlock and finalize).
We could potentially *always* call p.finalize and friends, but I'm not
sure if that make sense and in the case of a toml title block I don't
think I need/want that.
This avoids having a dependency on the toml Go library in this package.
> Add ParserFunc

- parser/block.go
- parser/options.go
- parser/options_test.go
This makes the function return the ast.Node, this also negates the need
to make addBlock, block, and finalize public or to give parser.Parser to
the function.
Fix the option_test.go to actually test things.
> BlockHook: better function signature

- README.md
- ast/node.go
- block_test.go
- html/renderer.go
- mmark_test.go
- parser/block.go
- parser/parser.go
- testdata/mmark.test
This adds detection for headers that start with `.#`. It adds the Mmark
extension, update the mmar test, adds some documentation.
I'm reusing the ast.Heading to have a maximum amount of code re-use.
> Mmark: add SpecialHeading

- ast/node.go
- html/renderer.go
- mmark_test.go
- parser/aside.go
- parser/block.go
- parser/parser.go
This implements asides, blockquote like paragraph prexifed with `A>`
instead of just a '>'
> Mmark: implement asides

- block_test.go
- mmark_test.go
- parser/block.go
- parser/parser.go
This gets rid of the various Mmark* extension types.
> Unify all Mmark extension under Mmark

- parser/block.go
- parser/include.go
- parser/include_test.go
- parser/options.go
- parser/parser.go
This adds a IncludesHook that returns the byte to be read. Error
handling is completely left to the client. By default when there is no
includehook we return nil for bytes read.
> Support includes

- parser/block.go
If the mmark extension is set and there is no caption we should still
add the block to the AST.
Caught by mmark testing.
> Add block for Mmark

- html/renderer.go
- testdata/mmark.test
Also export it, so it can be used directly in mmark/xml/renderer.go (I
had the exact copy of this code there)
Fixes #27
> Fix how classes are returned in block level attributes

- ast/node.go
- html/renderer.go
Implement the TODO and a method `String()` that returns a string for
AlignmentFlags.
Pondered doing the same for Matters and CitationTypes, but those are
more renderer dependent (and not standard).
> Make a String() function for AlignmentFlags

- parser/include.go
Of course, this happened. Fix off-by-one
Caught by mmark testing
> Fix off-by-one error in include parsing

- parser/block.go
- parser/include.go
- parser/include_test.go
Make the test table driven and fix bugs uncovered by the new test.
Mainly in the area of parsing the optional address specification between
block quotes.
> Fix include testing

- parser/block.go
- testdata/mmark.test
This is the same fix as for #40, but for quote block.
Add bare quote test to testdata/mmark.test as well for this.
> Add quote block even without caption

- ast/node.go
- html/callouts.go
- html/callouts_test.go
- html/renderer.go
- parser/callout.go
- parser/callout_test.go
- parser/inline.go
Add ast.Callout node that is detected in test and extra utils to parse
it in codeblock.
See https://mmark.nl/post/syntax/#callouts for what they are.
> Add callout parsing

- ast/node.go
- html/renderer.go
- parser/ref.go
- parser/ref_test.go
- testdata/mmark.test
This parsed (!item) as an index, subitems are allowed as well as making
the index primary (by adding another !: (!!item). The HTML output is
non-existent and there is no go in gomarkdown to render an index (left
to a custom renderer)
> parser: allow indices

- ast/node.go
- html/renderer.go
- parser/parser.go
- parser/ref.go
- testdata/mmark.test
To allow linking to indices by giving them an ID; without it an index
can not refer back to the actual index item from main index at the end
of the document.
> Add uniq ID to indices

- parser/block.go
- parser/include.go
- parser/include_test.go
- parser/options.go
- parser/parser.go
Bring back keeping a stack of included file because don't assume a CWD for the process.
The user of this lib still needs to do a little dance to get the correct path, keeping in mind the CWD, initial file (absolute or not). I now have this:
Fixes #54
~~~
// The initial file we are working on, empty for stdin and adjusted is we
// we have an absolute or relative file.
type Initial string
func NewInitial(s string) Initial {
if path.IsAbs(s) {
return Initial(path.Dir(s))
}
cwd, _ := os.Getwd()
if s == "" {
return Initial(cwd)
}
return Initial(path.Dir(filepath.Join(cwd, s)))
}
// path returns the full path we should use according to from, file and initial.
func (i Initial) path(from, file string) string {
if path.IsAbs(file) {
return file
}
if path.IsAbs(from) {
filepath.Join(from, file)
} …
> Include: take2

- html/renderer.go
- testdata/mmark.test
The link is local (by definition) add '#' to mark it as such.
> Cross reference: prepend '#'

- parser/block.go
- parser/caption.go
- testdata/mmark.test
This syntax was actually stolen from Pandoc, where it is used for
Tables (will update that, once those PRs are in). So leave the original
(from mmark1) syntax makes sense.
> Drop "Caption: " in favor of specific caption triggers

- ast/node.go
- block_test.go
- html/renderer.go
- parser/block.go
- parser/parser.go
This takes the syntax from kramdown: https://kramdown.gettalong.org/syntax.html#tables
It's not guarded by any parser extension, except the parser.Tables
> Table: parse table footers

- block_test.go
- html/renderer.go
- parser/block.go
- testdata/mmark.test
You can't make up you're own attributes, give special header the class
"special". Adjust all testcases.
`<hr>`: support block level attributes.
Add more tests for block level attributes.
Fix figure attributes, by re-adding the attribute to the inner block
(table, quote or code block).
Fixes #7
> Fix special section

- README.md
- ast/node.go
- html/renderer.go
- parser/block.go
Update the README with table footer syntax: fixes #77
Update the README and just point to mmark.nl instead of listing
all mmark syntax elements (again).
Fix multiple classes in headers.
Make header.Special a bool and rename it it IsSpecial. fixes #75 
> Update readme and other fixes

- html/renderer.go
- testdata/mmark.test
Just using matter is not legal in html5, `data-` is.
> matter: use data-matter

- html/renderer.go
For the blockattributes it is nice to be able to switch this to
something else.
> html: allow setting the tag for IDs

- parser/block.go
The block wasn't finalized leading to new content being add here.
Caught in mmark testing (and test case added).
> Table caption: add p.finalize

- README.md
- ast/node.go
- html/esc.go
- html/renderer.go
- parser/esc.go
- parser/esc_test.go
- parser/inline.go
- parser/parser.go
Other markdown parser put this behind an extension; do the same here:
extension: SuperSubscript.
Detect sequences between ^ and ~ as super and subscript respectively.
> Add super and subscript support

- mmark_test.go
- parser/inline.go
- testdata/mmark.test
The +1 lead to out of bounds on the data slice.
Add test in testdata/mmark.test as well.
> super-subscript: fix index out of range

- ast/node.go
- html/renderer.go
- parser/parser.go
This adds an (empty) *ast.Footnote before the footnotes are added.
This can be used to customize the it, i.e. putting it in a new section.
The HR output is put behind a flag html.FootnoteNoHRTag to suppress that
as well.
Fixes #80
> Allow hooking into footnote generation

- block_test.go
- parser/block.go
port c455fd41 from https://github.com/russross/blackfriday/ v2 branch
over.
Add test case for list in list detection.
Still doesn't detect definition lists in lists though.
> Fix list in lists: port fix from blackfriday

- parser/options.go
- parser/parser.go
add SkipFootnoteList flag to skips adding the footnote list (regardless
if they footnotes themselves are parsed).
This allows you to remove footnotes from the output (so they get
parsed), but still suppress the footnote list.
Fixes #91
> Add parser flags

- parser/block.go
One char fix: | --> &
Check was wrong, but happen to work.
> Aside check uses 'or' should be 'and'

- block_test.go
- parser/block.go
This fixes the same issue, but in this code base. Patching was done
manual, but with minimal effort.
full details:
~~~
% wget https://patch-diff.githubusercontent.com/raw/russross/blackfriday/pull/372.patch
...
Saving to: ‘372.patch’
~~~
Edit `372.patch` to fix the path nams -> a/block.go -> a/parser/block.go etc.
~~~
% patch -p1 --dry-run < 372.patch
checking file block_test.go
Hunk #1 succeeded at 1513 with fuzz 2 (offset 55 lines).
checking file parser/block.go
Hunk #1 succeeded at 1571 (offset 325 lines).
Hunk #2 succeeded at 1605 (offset 325 lines).
checking file parser/block.go
Hunk #1 FAILED at 1293.
1 out of 1 hunk FAILED
checking file parser/block.go
Hunk #1 FAILED at 1280.
1 out of 1 hunk FAILED
checking file block_test.go
Hunk #1 …
> port https://github.com/russross/blackfriday/issues/239

- parser/block.go
- parser/figures.go
- parser/parser.go
- testdata/mmark.test
This adds new block syntax that allows you to put multiple figures (or
other block elements) in a larger figure; essentially having subfigures.
Is only enabled when the Mmark extension is on.
The trigger is `!---` as it looks like a code block. This also allows
you to set block level attributes on the element.
See https://mmark.nl/post/syntax/#figures-and-subfigures for some extra
wording on the new syntax.
> parser: Implement Subfigures

- block_test.go
- parser/block.go
See the detail in #102. This make a list containing a code block a list
containing a block. Add specific test case of a code block in a list.
Fixes #102
> parser: fix def. list containing a codeblock

- html/renderer.go
- testdata/mmark.test
Render citations more sanely add `<sup>CITATION</sup>` as the default.
Also add the infra for this to be overruled.
> mmark citation: create option for rendering

- block_test.go
- parser/block.go
This reverts PR #101, more trouble than it's worth. This still leaves the
original problem of having a list in a code block not work in a list.
> revert #101

- html/renderer.go
Put the generator text in a public var so it can be overridden by
renderers that add to it.
> Allow html.Renderers' generator meta tag to be overridden

- block_test.go
- parser/block.go
Because we are a line by line parser with are too late to detect nested
definition lists. The fix implemented here detects that we are in this
situation and then backtracks to search for the beginning of the
previous line and starts the sublist there.
This doesn't break any existing test. Added def-in-def tests for this
particular case.
> Fix definition list in definition lists

- inline_test.go
- parser/inline.go
- parser/parser.go
Fix the infinite loop when there is a self-refer footnote by checking if
the reference is already added into parser.notes.
It also fixes of creating duplicate footnotes through this modification.
Add coresponding testcase.
Original PR: https://github.com/russross/blackfriday/pull/366
Fixes: https://github.com/mmarkdown/mmark/issues/25
> Fix duplicate and recursive footnotes

- parser/block.go
- parser/parser.go
The ability to toggle Includes, regardless of Mmark can be imported:
make a separate extenions: "Includes"
I'm writing a renderer that outputs Markdown, it is impossible to hook
into the include code to say: "leave those alone for now", so having a
new Extension seems like the cleanest way of doing this.
> Add Includes extension

- parser/caption.go
drop sanitize anchor name as it leads to underscores being changed to
dashes, which is suppresing.
Make the detection simpler and check if there is trailing whitespace,
which we allow.
Add test case in mmark repo.
> parser: caption: allow trailing whitespace.

- ast/node.go
- parser/citation.go
- parser/citation_test.go
mmark 2 promised to implement this: allow a citation suffix:
[@!RFC1034, p. 144]. Implement this by splitting on the comma.
Add multiple tests for this new behavior.
> mmark: allow citation suffix

- ast/node.go
- parser/inline.go
Keep track if a link or footnote was deferred. This makes it possible to
do this again when generating (formatted) markdown output. I.e. now all
deferred links/footnotes become inline because it does not know that
some of them had been deferred.
Without this patch:
Footnote^[footnote *with* stuff ]
With this patch:
Footnote[^id]
[^id]: footnote *with* stuff
Where the later is how to the original markdown file was formatted.
> links: keep deferred status

- README.md
- ast/node.go
- html/renderer.go
- parser/inline.go
- parser/parser.go
A backslash-space is a non-blocking-space that is recognized when
enabling the NonBlockingSpace extension.
Fixes: #128
> Add non-blocking-space

- md/md_renderer.go
Thanks for the awesome project. I was trying to render markdown with the `md` package and found that my code panics if it contains image, which then led me to finding this...
Hope the panic was not intentional.
> md: Do not panic in when render image

- inline_test.go
- parser/inline.go
I need this in order to be able to use `ReferenceOverride` for custom links, like `[some-page-identifier]` where the link text needs to be overridden.
> Fix overriding reference text for custom references

- html/doc.go
Fix misnomer in sample code in html docs.
> html/doc.go: fix RenderOptions -> RendererOptions

- inline_test.go
- parser/inline.go
Add ^ because it will be detected for <sup>. Not the <sup> is an
extension but because of the `var escapeChars =` this can't be checked
at that point; I think this adding it can't do any harm.
Extend the test case a little for specially this case.
See https://github.com/mmarkdown/mmark/issues/104 for some background.
> Add '^' to escapeChars

- html/renderer.go
- inline_test.go
`rel=noopener` is an important flag to use. See https://mathiasbynens.github.io/rel-noopener/
> Add NoopenerLinks

- block_test.go
- html/renderer.go
- testdata/TOC.tests
If you enable HeadingIDs, e.g. 
And also want to output TOC, the TOC will override your custom id and make generic `toc_<number>` ids instead.
> Fix TOC overriding HeadingIDs

- parser/block.go
- testdata/NestedDefinitionList.tests
block elements are detected by an empty line, but a list is also a block
element, so if we detect a list change (in list) we also set the
`ListItemContainsBlock` to true.
This parses all tests with a minimal change - I think it's the correct
way of doing this.
> lists in lists: make it contain a block element

- parser/block.go
I added a few lines so that custom renderHooks can detect which kind of horizontal rule was used.
This change does not in any way affect how the HR is rendered normally.
> Added HR literal support

- helpers_test.go
when you run tests with this change it will look like this;
```
--- PASS: TestReference (0.05s)
--- PASS: TestReference/Amps_and_angle_encoding (0.00s)
--- PASS: TestReference/Auto_links (0.00s)
--- PASS: TestReference/Backslash_escapes (0.00s)
--- PASS: TestReference/Blockquotes_with_code_blocks (0.00s)
--- PASS: TestReference/Code_Blocks (0.00s)
--- PASS: TestReference/Code_Spans (0.00s)
--- PASS: TestReference/Horizontal_rules (0.00s)
--- PASS: TestReference/Inline_HTML_(Advanced) (0.00s)
--- PASS: TestReference/Inline_HTML_(Simple) (0.00s)
--- PASS: TestReference/Inline_HTML_comments (0.00s)
--- PASS: TestReference/Links,_inline_style (0.00s)
--- PASS: TestReference/Links,_reference_style (0.00s)
--- PASS: TestReference/Links,_shortcut_references (0.00s)
--- PASS: …
```
> use t.Run() to make it easier to only run a subset of the testdata

- parser/block.go
- testdata/Table.tests
this will parse a table without a header row as well, for example:
```
---|---
c | d
```
> Parse headless table

- ast/node.go
- html/renderer.go
- html_renderer_test.go
as an alternative to https://github.com/gomarkdown/markdown/pull/176 this PR adds a way to add additional attributes to links which the HTML renderer will include when rendering the link.
> add support for RenderNodeHook to add additional attributes to links.

- html/renderer.go
- inline_test.go
I use gomarkdown/markdown for server side rendering, and I was initially going to create a custom renderer to stop the server-side rendering result from actually lazy loading images on the front end (because the front end supported lazy loading while the back end didn't), but I figured this flag could come in handy for others.
Basically, setting this new `LazyLoadImages` flag would automatically include `loading="lazy"` in `img` elements.
For more context on what this does: https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading
> Add LazyLoadImages flag

- parser/block.go
- testdata/Table.tests
If a table is the last thing in the file, and there's no terminating newline
in the file, the parser will try to read past the end of the byte slice,
leading to a panic. This fixes the problem and adds a test which illustrates
the problem.
> Fix panic with table parsing

- parser/block_table.go
- testdata/Table.tests
Fix problem with parsing tables with empty fields in the header. 
[Issue 194](https://github.com/gomarkdown/markdown/issues/194)
> fix-tables-with-empty-header-fields-parsing

- parser/block.go
- parser/block_table.go
Codeblocks, tables and quotes may include a caption, we need to check
for this at parse time and adjust the bytes read. If not there is a
weird disconnect between "doing it inline" and using it via an include.
Take this small md file:
~~~ markdown
<{{testdata/includes.c}}
Figure: A sample function.
And some other text.
~~~
Before:
~~~
CodeBlock 'main() int {\n        return 0\n}\n'
Paragraph
Text 'Figure: A sample function.'
Paragraph
Text 'And some other text.'
~~~
After:
~~~
CaptionFigure
CodeBlock 'main() int {\n        return 0\n}\n'
Caption
Text 'A sample function.\n'
Paragraph
Text 'And some other text.'
~~~
which will then do the right thing. Make 'Figure: ", etc. constants as
they are used more than once.
> Check for caption after (code)include

- parser/block.go
- testdata/OrderedList.tests
This is allowed in commonmark and there is actually a comment in the
source saying so much.
Add check to oliPrefix to check for ) and in the list-gathering function
set the delimiter found.
> Allow ) as delimiter in ordered lists

- parser/block.go
- parser/block_table.go
- testdata/Table.tests
Tables are block level entities and as such should also break a
paragraph, just like lists, codeblocks, etc.
Add the missing the check in the paragraph() function. Needed to alter
the tableHeader() function to not added a TableHeader if detected, added
doRender bool for that.
testdata/Tables.tests extended with a test that has text before the
table and double checked it failed without the new code.
Fixes: #214
> Make tables break a paragraph

- parser/block_table.go
- testdata/Table.tests
A codespan can contain a `|`. This messes up the table parsing because
the delimiter there is also `|`. Check for a codespan in the table
(header, row or footer) and simply skip to the end of it and resume scanning.
table footer
> Fix codespan inside a table

- html/doc.go
`renderHookCodeBlock` is outdated and doesn't work
> Fix an example in the html doc

- inline_test.go
- parser/block.go
- parser/inline.go
- parser/parser_test.go
Fixes https://github.com/gomarkdown/markdown/issues/124
There are a couple of tests that start failing when this PR is applied, but I think that actually the expected value must be updated. These are the tests that fails:
**TestFootnotes**
Input:
```md
Input:
testing long[^b] notes.
[^b]: Paragraph 1
Paragraph 2
```
some code
```
Paragraph 3
No longer in the footnote
```
Expected: 
```html
<p>testing long<sup class="footnote-ref" id="fnref:b"><a href="#fn:b">1</a></sup> notes.</p>
<p>No longer in the footnote</p>
<div class="footnotes">
<hr />
<ol>
<li id="fn:b"><p>Paragraph 1</p>
<p>Paragraph 2</p>
<p><code>
some code
</code></p>
<p>Paragraph 3</p></li>
</ol>
</div>
```
Got:
```html
<p>testing long<sup class="footnote-ref" id="fnref:b"><a href="#fn:b">1</a></sup> notes.</p>
<p>No longer …
```
> Fix fenced codeblocks inside lists

- md/md_renderer.go
- md/md_renderer_test.go
This should fix the markdown rendering of the lists, keeping the parsed bullet char and indenting the nested lists.
> Fix markdown rendering of lists

- md/md_renderer.go
- md/md_renderer_test.go
Fix the markdown rendering of the Heading. Basically, we always want a newline after outputting the heading text.
> Fix markdown rendering of heading

- md/md_renderer.go
- md/md_renderer_test.go
Hello! Recently found that the markdown renderer renders html blocks incorrectly. According to [spec](https://daringfireball.net/projects/markdown/syntax#html) block level html must be separated from surrounding content by blank lines. Seems like my naive fix could help.
So, for example, this markdown:
<table>
<tr>
<td>Foo</td>
</tr>
</table>
Renders as:
<table>
<tr>
<td>Foo</td>
</tr>
</table>
> fix markdown html block rendering

- html/renderer.go
- inline_test.go
- internal/valid/valid.go
- parser/inline.go
The vars had duplicate content. I followed the wish expressed in the `TODO` and move them in a separate (internal) package. I also noticed that `mailto:` had slashes after the semicolon which made no sense.
> Move ValidUris and ValidPaths in a separate package

- helpers_test.go
- html/renderer.go
- inline_test.go
- internal/valid/valid.go
- parser/inline.go
- parser/parser.go
If set, the hook overrides the default `IsSafeURL` and allows users of the library to decide which URIs are safe to keep. This asked for some refactoring which I made into separate commits. I think the PR is quite big and thought it would be best to review it as two separate PRs. However, I didn't communicate my intentions and this was met with [misunderstanding](https://github.com/gomarkdown/markdown/pull/251). This time around I'm submitting the branch as is. I have left some TODOs which I will take care once this gets some eyeballs.
> Add IsSafeURLOverride

- parser/inline.go
- testdata/Links, inline style.html
- testdata/Links, inline style.text
[](http://bla) is considered a link in CommonMark and GFM, support this
here too. It does not generate something a user can click so it's a bit
questionable.
Updated tests as well.
> Allow "empty links"

- html/renderer.go
- inline_test.go
- parser/inline.go
- testdata/Links, inline style.html
See 558d915, this supports the reverse as well: `[foo]()` is turned into
a empty ahref - also affects the img rendering. Checked with
https://commonmark.org/help/tutorial/07-links.html what CommonMark
thinks of this and it says 'OK'
This indeed trickers a crash when accessing uLink[0], fixes that and
updated the tests.
Closes #257
> Support [foo]() syntax

- ast/node.go
- parser/ref.go
- parser/ref_test.go
See issue #223 for initial discussion. This is implemented in this PR,
added tests in ref_test.go.
Only issue is that: `(#y,es)` is now a valid reference, with the ID
being set to "y" - which may be surprising? Potentially this can be
hidden behind (another) extension?
The XMLv3 standard allows a 'format' attribute, so this is not going
away and provides a neat way to be able to set that attribute.
> Allow suffix for cross references

- ast/node.go
- ast/node_test.go
...which allows a Leaf to be used with RemoveFromTree, see #262
Rather than changing `RemoveFromTree` to check for leaves, it made more sense to me to allow setting "empty" children on a leaf.
> Allow setting empty children on Leaf node

- parser/parser.go
this is now the same link as in the `README.md`
> fix link to mmark in comment

- parser/inline.go
- testdata/Backslash escapes.html
- testdata/Backslash escapes.text
- testdata/Markdown Documentation - Syntax.html
- testdata/Markdown Documentation - Syntax.text
Closes #282
As suggested by @alexwennerberg, the fix is a simple 1 line change, adding the `$` to the slice of backslash escape-able characters.
The `\$` sequence was also added to the testdata.
> Fix: escape `$`

- examples/inline.go
- parser/parser.go
Very minor change.
Example edited as well to use the exported function.
> Export inlineParser to allow more concise and readable custom parser functions 

- parser/block.go
- parser/block_test.go
SVG is now part of HTML 5 and the SVG element a valid top-level element. The other SVG element, however, do not stand on their own. https://html.spec.whatwg.org/dev/embedded-content-other.html#svg-0
Note: This does not match up with the definition of CommonMark HTML blocks. CommonMark does not recognize the SVG element as a HTML block. In this respect, however, it would seem that CommonMark is lagging behind. https://spec.commonmark.org/0.31.2/#html-blocks
> Add SVG element

- md/md_renderer.go
- md/md_renderer_test.go
This PR fixes line breaks in the output of the markdown renderer.
Currently, if a markdown document is parsed and rendered using this `markdown` library, some relevant line breaks are lost:
- double line breaks after paragraphs
There are other (cosmetic) line breaks that are lost, but don't affect the validity of the markdown output:
- line breaks after headings
- line breaks after lists
There are some line-breaks that are added that should not be added:
- A new line at the end of code blocks is added. 
Input:
```md
Paragraph 1
Paragraph 2
- List item 1
- List item 2
Paragraph 3
\```
some code
\```
```
Is currently rendered as:
```md
Paragraph 1
Paragraph 2
- List item 1
- List item 2
Paragraph 3
\```
some code
\```
```
<details>
```go
func TestPR(t *testing.T) {
input := …
```
> Fixed line breaks in rendered markdown output

- parser/inline.go
- parser/parser.go
I have added hashtags to my Markdown. When rendered, these produce a search link. My problem was that sometimes the link text contained something that looked like a hashtag. Specifically: `[oh #ok](ok)` should produce `<a href="ok">oh #ok</a></p>` and not `<a href="ok">oh <a class="tag" href="/search/?q=%23ok">#ok</a></a></p>`.
I can fix this if `p.InsideLink` is accessible to my code:
```go
// hashtag returns an inline parser function. This indirection is
// required because we want to receive an array of hashtags found.
// The hashtags in the array keep their case.
func hashtag() (func(p *parser.Parser, data []byte, offset int) (int, ast.Node), *[]string) {
hashtags := make([]string, 0)
return func(p *parser.Parser, data []byte, offset int) (int, ast.Node) {
if p.InsideLink { // HERE …
```
> Make parser.InsideLink public

- README.md
Thank you for this project! I've always went straight to your docs, but today I started a new project and I tried copy/pasting the example.  When running with `go run` I noticed that both os and markdown/ast are imported and unused.
```
$ go run main.go
./main.go:4:2: "os" imported and not used
./main.go:7:2: "github.com/gomarkdown/markdown/ast" imported and not used
```
> Fix the example so that it compiles

- md/md_renderer.go
- md/md_renderer_test.go
Add a flag for the markdown renderer, renderLinksInFooter, that can be used to render link definitions in the footer of the document, rather than inline.
Example usage:
renderer := NewRenderer()
renderer.WithOpts(&RendererOptions{Flags: flags})
result := markdown.Render(input, renderer)
Example input: 
"This is an [example](https://example.com) and another [website](https://github.com)."
Example output: 
"This is an [example] and another [website].
[example]: https://example.com
[website]: https://github.com
"
> Add flag to render link definitions in footer

- md/md_renderer.go
- md/md_renderer_test.go
Fix how sub-lists within a list are rendered by the markdown renderer - don't insert an extra newline after the sub-list.
Resolves https://github.com/gomarkdown/markdown/issues/339 and https://github.com/gomarkdown/markdown/issues/340.
> Fix extra newlines in sub-lists in markdown renderer
